backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'source/assets/img/uploads'
public_folder: '/assets/img/uploads'
collections:
  # Our blog posts
  - name: 'work' # Used in routes, e.g., /admin/collections/blog
    label: 'Project' # Used in the UI
    folder: 'work' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'When', name: 'when', widget: 'number' }
      - { label: 'Where', name: 'where', widget: 'string' }
      - label: 'Images'
        name: 'images'
        widget: 'list'
        field:
          label: 'Image'
          name: 'image'
          widget: object
          fields:
            - label: 'Cloudinary ID'
              name: 'id'
              widget: 'string'
            - label: 'Caption'
              name: 'caption'
              widget: 'text'
      - { label: 'Body', name: 'body', widget: 'markdown' }
